ALTER TABLE tasks ADD COLUMN reviewer_id BIGINT;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_reviewer
    FOREIGN KEY (reviewer_id) REFERENCES project_members (id) ON DELETE SET NULL;

CREATE TABLE submission_criterion_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    source_criterion_id BIGINT,
    content VARCHAR(1000) NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT fk_submission_criterion_snapshots_submission
        FOREIGN KEY (submission_id) REFERENCES task_submissions (id) ON DELETE CASCADE,
    CONSTRAINT uk_submission_criterion_snapshots_position UNIQUE (submission_id, position),
    CONSTRAINT chk_submission_criterion_snapshots_position CHECK (position >= 0)
);

CREATE TABLE submission_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    decision VARCHAR(32),
    message VARCHAR(5000),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    submitted_at TIMESTAMP(6),
    CONSTRAINT fk_submission_reviews_submission
        FOREIGN KEY (submission_id) REFERENCES task_submissions (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_reviews_reviewer
        FOREIGN KEY (reviewer_id) REFERENCES project_members (id),
    CONSTRAINT uk_submission_reviews_reviewer UNIQUE (submission_id, reviewer_id),
    CONSTRAINT chk_submission_reviews_status CHECK (status IN ('DRAFT', 'SUBMITTED')),
    CONSTRAINT chk_submission_reviews_decision CHECK (decision IS NULL OR decision IN ('APPROVED', 'CHANGES_REQUESTED')),
    CONSTRAINT chk_submission_reviews_shape CHECK (
        (status = 'DRAFT' AND decision IS NULL AND submitted_at IS NULL)
        OR (status = 'SUBMITTED' AND decision IS NOT NULL AND submitted_at IS NOT NULL)
    )
);

CREATE TABLE submission_criterion_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_review_id BIGINT NOT NULL,
    criterion_snapshot_id BIGINT NOT NULL,
    result VARCHAR(32),
    comment VARCHAR(2000),
    CONSTRAINT fk_submission_criterion_reviews_review
        FOREIGN KEY (submission_review_id) REFERENCES submission_reviews (id) ON DELETE CASCADE,
    CONSTRAINT fk_submission_criterion_reviews_snapshot
        FOREIGN KEY (criterion_snapshot_id) REFERENCES submission_criterion_snapshots (id) ON DELETE CASCADE,
    CONSTRAINT uk_submission_criterion_reviews_item UNIQUE (submission_review_id, criterion_snapshot_id),
    CONSTRAINT chk_submission_criterion_reviews_result CHECK (result IS NULL OR result IN ('PASSED', 'FAILED'))
);

CREATE INDEX idx_submission_reviews_submission_status ON submission_reviews (submission_id, status);
